include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Relative imports make it easier to distinguish between API and lib imports
    always_use_package_imports: false
    avoid_relative_lib_imports: false
    prefer_relative_imports: true
